name: starlist
description: An app for keeping track of your content consumption.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  http: ^1.1.0
  dio: ^5.3.3
  url_launcher: ^6.2.2
  youtube_player_flutter: ^8.1.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^5.1.0
  intl: ^0.20.2
  uuid: ^4.1.0
  image_picker: ^1.0.5
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  flutter_local_notifications: ^19.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.0
  share_plus: ^10.0.0
  rxdart: ^0.27.7
  path_provider: ^2.1.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  # - assets/icons/
