name: starlist
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0
  font_awesome_flutter: ^10.9.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icons/services/
