name: starlist_improved
description: Starlistアプリの改善版ランキング機能
version: 1.0.0
homepage: https://github.com/shochaso/starlist

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  dio: ^5.0.0
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  mockito: ^5.4.0
  supabase_flutter: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
