# Claude AI を利用して Issue や Pull Request に応答する GitHub Action
name: Claude Code Actions

on:
  # Issue が作成または編集された時に実行
  issues:
    types: [opened, edited]
  # Pull Request が作成または編集された時に実行
  # pull_request_target はフォークからのPRにも対応でき、安全にシークレットを利用するために推奨されます
  pull_request_target:
    types: [opened, edited]

jobs:
  claude_action:
    runs-on: ubuntu-latest
    # Action が Issue や PR にコメント・コミットするために必要な権限を付与
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      # Step 1: Sturdy社のClaude Actionを利用
      # [修正] 存在しないnpmパッケージをインストールする代わりに、実績のあるGitHub Actionを使用します。
      # これにより、Node.jsのセットアップやnpmインストールが不要になり、ワークフローがシンプルになります。
      - name: Run Claude Action
        uses: sturdy-dev/claude-action@v1
        with:
          # GitHub Secretsに登録したAnthropic APIキーを渡します
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # GitHubが自動的に生成するトークンを渡します
          github-token: ${{ secrets.GITHUB_TOKEN }}

