# claude.yaml (これは例です。具体的なワークフローはGRLL氏のリポジトリのものを参照してください)
name: Claude Code Actions

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

jobs:
  claude_action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Claude Code Actions CLI
        run: npm install -g @anthropic-ai/claude-code

      - name: Run Claude Code Action
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }} # ここでシークレットを参照
        - name: Run Claude Code Action
        run: |
          echo "Starting Claude Code Action..."
          # claude-code-actions CLI を実行してIssueの内容を処理します。
          # 実際のコマンドはツールの仕様に合わせてください。
          claude code-actions --issue-number ${{ github.event.issue.number }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # アクションがIssueを読み取るためにGITHUB_TOKENが必要な場合が多いです
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}} --repo ${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
