# claude.yaml (これは例です。具体的なワークフローはGRLL氏のリポジトリのものを参照してください)
name: Claude Code Actions

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

jobs:
  claude_action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Claude Code Actions CLI
        run: npm install -g @anthropic-ai/claude-code

      - name: Run Claude Code Action
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }} # ここでシークレットを参照
        run: |
          # issueの本文を読み込み、Claudeに指示を出すコマンドを実行
          # 例: claude code-actions --issue-body "${{ github.event.issue.body }}" --issue-number "${{ github.event.issue.number }}"
          # 詳細なコマンドはGRLL氏のリポジトリのドキュメントを参照して、リポジトリの目的と合わせて調整してください
          echo "Claude Code Action is running..."
          # ここに具体的なClaude Code Actionのコマンドを記述します。
          # 例えば、Pull Requestのコードを分析してコメントする場合など。
          # GRLL氏のフォークされたリポジトリのREADMEやquickstart guideを参照し、
          # 実際の使用例に合わせてコマンドを記述してください。
          # 一般的には以下のような形式になる可能性があります（あくまで例です）:
          # claude code-actions review-pr --issue-number ${{ github.event.issue.number }} --repo ${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
