name: Claude Code Actions

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

jobs:
  claude_action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Correct Claude Code Actions CLI
        run: npm install -g <ここに正しいパッケージ名を書く>

      - name: Run Correct Claude Code Action
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting the correct Claude Action..."
          <ここに正しいコマンドを書く> --issue-number ${{ github.event.issue.number }} --repo ${{ github.repository }}
