# Claude AI を利用して Pull Request を自動レビューする GitHub Action
name: AI Code Review

# permissionsブロックをトップレベルに定義し、ワークフロー全体の権限を設定
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Run AI Code Reviewer
        # [修正] 存在しないActionの代わりに、コードレビューに特化した実績のあるActionを使用します。
        uses: codereviewer-ai/codereviewer-ai@v1.0.2
        with:
          # GitHubが提供するトークンを渡します
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # [必須] Anthropic APIキーを渡します
          # GitHubリポジトリの Secrets に ANTHROPIC_API_KEY として設定してください
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # [必須] AIプロバイダーとして 'anthropic' を指定
          LLM_PROVIDER: "anthropic"
          
          # [任意] 使用するClaudeのモデルを指定（例: claude-3-opus-20240229, claude-3-sonnet-20240229, claude-3-haiku-20240307）
          # コストとパフォーマンスのバランスが良いHaikuモデルを推奨します
          LLM_MODEL: "claude-3-haiku-20240307"
