name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply Database Migrations
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
          supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
      - name: Update Task Status
        run: |
          # Mark scheduled tasks as complete based on their status in the code
          ./scripts/task_completion_check.sh
          
      - name: Deploy Flutter Web (if applicable)
        run: |
          # If you have a web version, you can deploy it here
          echo "Deploying web version is not configured yet" 